import { useNavigate } from "react-router-dom";
import { GetRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";
import { useState } from "react";

const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    Name: "",
    promt: "",
    photo: "",
  });

  const [generatingImage, setGeneratingImage] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = () => {};

  const handleChange = (e) => {};

  const  handleSurpriseMe = (e) => {};

  return (
    <section>
      <div>
        <h1 className=" font-extrabold text-[#222328] text-[32px]">
          Generate Image
        </h1>
        <p className=" mt-2 text-gray-400 max-w-[500px] text-[16px]">
          Create imaginative and visually stunning Images generated by Dalle AI
          and Showcase them in community.
        </p>
      </div>

      <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
        <div className=" flex flex-col gap-5">

          <FormField
            labelName="Your Name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handleChange={handleChange}
          />

          <FormField
            labelName="Prompt"
            type="text"
            name="promt"
            placeholder="a bowl of soup that looks like a monster, knitted out of wool"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
        </div>
      </form>
    </section>
  );
};

export default CreatePost;
